print("-=-" * 30)
Num1 = int(input("Digite 5 números inteiros juntos: "))
print("--" * 20)
print("A soma dos números é: ", Num1+Num1 )
print("--" * 20)
print("A multiplicação desses números é: ", Num1*Num1)
print("--" * 20)
Num1 = (str(Num1))
print("O primeiro número é '{}', o segundo '{}', o terceiro '{}', o quarto '{}' e o quinto '{}'." .format(Num1[0], Num1[1], Num1[2], Num1[3], Num1[4]))
print("-=-" * 30)